CREATE TABLE `livros` (
  `id` int not null auto_increment primary key,
  `titulo` varchar(90),
  `categoria` varchar(60),
  `autor` varchar(60),
  `editora` varchar(60),
  `tipo` varchar(60),
  `estado` tinyint(1),
  `recebido` boolean
  `pathi` varchar(90),
  `relation` int
);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,	'One piece n°1	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°2	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°3	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°4	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°5	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°6	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°7	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°8	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°9	','Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°10'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°11'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°12'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°13'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°14'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°15'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°16'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°17'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°18'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°19'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°20'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°21'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°22'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°23'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°24'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°25'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°26'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°27'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°28'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°29'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°30'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°31'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°32'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°33'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°34'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°35'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°36'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°37'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°38'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°39'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°40'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°41'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°42'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°43'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°44'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°45'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°46'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°47'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°48'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°49'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°50'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°51'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°52'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°53'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°54'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°55'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°56'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°57'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°58'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°59'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°60'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°61'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°62'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°63'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°64'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°65'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°66'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°67'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°68'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°69'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°70'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°71'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°72'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°73'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°74'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°75'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°76'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°77'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°78'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°79'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°80'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°81'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°82'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°83'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°84'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°85'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°86'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°87'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°88'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°89'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°90'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°91'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°92'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°93'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°94'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°95'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°96'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°97'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°98'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°99'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°100'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°101'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°102'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°103'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°104'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°105'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°106'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°107'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°108'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2),
(default,	'One piece n°109'	,'Aventura'	,'Eiichiro Oda'	,'Panini'	,'Manga',1,1,null	,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°72','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°1','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°2','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°3','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°4','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°5','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°6','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°7','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°8','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°9','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°9','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°10','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°11','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°12','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°13','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°14','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°15','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°17','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°19','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°20','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°21','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°22','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°23','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°24','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°25','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°26','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°27','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°28','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°29','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°30','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°31','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°32','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°33','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°34','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°35','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°36','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°37','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°38','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°39','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°41','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°42','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°43','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°44','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°45','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°46','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°47','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°48','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°49','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°50','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°51','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°52','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°53','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°54','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°55','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°56','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°57','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°59','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°61','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°62','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°64','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°65','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°66','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°67','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°68','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°69','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2),
(default,'One piece n°70','Aventura','Eiichiro Oda','Corand','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece Yellow Grandes Elementos','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Grande Arquivo de Dados','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Grande Arquivo de Dados','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Red Grandes Personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Red Grandes Personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Green Peças Secretas','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Green Peças Secretas','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Wanted!','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Deep Mundo dos personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°1','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°2','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°3','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°4','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°5','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°6','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°7','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°7','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°9','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°10','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°11','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°12','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°13','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°14','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°15','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°16','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°17','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°18','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°19','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2);

