CREATE TABLE `livros` (
  id int not null auto_increment primary key,
  titulo varchar(90),
  categoria varchar(60),
  autor varchar(60),
  editora varchar(60),
  tipo varchar(60),
  estado tinyint(1),
  recebido boolean,
  pathi varchar(90),
  relation int,
  valor int);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°1','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°2','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°3','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°4','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°5','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°6','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°7','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°8','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°9','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°10','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°11','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°12','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°13','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°14','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°15','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°17','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°19','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°20','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°21','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°22','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°23','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°24','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°25','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°26','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°27','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°28','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°29','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°30','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°31','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°32','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°33','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°34','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°35','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°36','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°37','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°38','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°39','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°41','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°42','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°43','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°44','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°45','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°46','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°47','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°48','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°49','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°50','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°51','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°52','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°53','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°54','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°55','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°56','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°57','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°59','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°61','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°62','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°64','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°65','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°66','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°67','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°68','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°69','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°70','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°71','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°72','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°73','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°74','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°75','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°76','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°77','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°78','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°79','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°80','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°81','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°82','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°83','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°84','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°85','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°86','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°87','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°88','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°89','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°90','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°91','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°92','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°93','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°94','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°95','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°96','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°97','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°98','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°99','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°100','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°101','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°102','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°103','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°104','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°105','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°106','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°107','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°108','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°109','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°72','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°1','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°2','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°3','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°4','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°5','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°6','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°7','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°8','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°9','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°9','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°10','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°11','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°12','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°13','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°14','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°15','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°17','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°19','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°20','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°21','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°22','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°23','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°24','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°25','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°26','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°27','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°28','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°29','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°30','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°31','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°32','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°33','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°34','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°35','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°36','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°37','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°38','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°39','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°41','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°42','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°43','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°44','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°45','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°46','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°47','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°48','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°49','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°50','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°51','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°52','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°53','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°54','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°55','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°56','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°57','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°59','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°61','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°62','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°64','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°65','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°66','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°67','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°68','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°69','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°70','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece Yellow Grandes Elementos','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Grande Arquivo de Dados','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Grande Arquivo de Dados','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Red Grandes Personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Red Grandes Personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Green Peças Secretas','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Green Peças Secretas','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Wanted!','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Deep Mundo dos personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°1','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°2','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°3','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°4','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°5','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°6','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°7','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°7','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°9','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°10','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°11','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°12','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°13','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°14','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°15','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°16','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°17','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°18','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°19','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Dragon Ball n°1','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°2','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°3','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°4','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°5','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°6','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°7','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°8','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°9','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°10','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°11','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°12','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°13','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°14','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°15','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°16','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°17','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°18','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°19','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°20','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°21','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°22','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°23','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°24','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°25','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°26','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°27','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°28','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°29','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°30','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°31','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°32','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Dragon Ball Z n°1','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°2','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°3','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°4','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°5','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°6','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°7','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°8','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°9','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°10','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°11','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°12','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°13','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°14','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°15','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°16','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°17','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°18','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°19','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°20','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°21','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°22','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°23','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°24','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°25','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°26','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°27','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°28','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°29','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°30','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°31','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°32','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°33','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°34','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°35','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°35','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°36','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°37','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°38','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°39','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°40','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°41','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°42','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°43','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°44','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°45','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°46','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°47','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°48','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°49','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°50','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°51','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,	'Dragon Ball n°1','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°2','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°3','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°4','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°5','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°6','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°7','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°8','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°9','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°10','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°11','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°12','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°13','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°14','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°15','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°16','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°17','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°18','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°19','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°20','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°21','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°22','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°23','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°24','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°25','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°26','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°27','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°28','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°29','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°30','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°31','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°32','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°33','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°34','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°35','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°36','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°37','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°38','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°39','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°40','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°41','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°42','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2);


insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,	'Enciclopédia Dragon Ball Z A lenda de Son Goku','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°3','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°4','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°5','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°6','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°7','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°8','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°9','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°10','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°11','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°12','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°13','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°14','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°15','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°16','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°17','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°18','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°19','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°20','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°21','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°22','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°23','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°24','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°25','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°26','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°27','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°28','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°29','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°30','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°31','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°32','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°33','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°34','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°35','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°36','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°37','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°38','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°39','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°40','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°41','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°42','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°43','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°44','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°45','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°46','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°47','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°48','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°1','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°3','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°4','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°5','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°6','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°7','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°8','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°9','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°10','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°11','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°12','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°13','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°14','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°15','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°16','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°17','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°18','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°19','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°20','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°21','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°22','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°23','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°24','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco Episódio G n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°3','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°4','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°5','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°6','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°7','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°8','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°9','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°10','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°11','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°12','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°13','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°13','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°14','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°14','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°15','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°15','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°16','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°17','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°18','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°19','Aventura','Masami Kurumada','Conrad','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°20','Aventura','Masami Kurumada','Conrad','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco Anime Classies I n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Anime Classies I n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Anime Classies II n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Anime Classies II n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Gigantomaquia n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Gigantomaquia n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco n°1','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°2','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°3','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°4','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°5','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°6','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°7','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°8','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°9','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°10','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°11','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°12','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°13','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°14','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°15','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°16','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°17','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°18','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°19','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°20','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°21','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°22','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°23','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°24','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°25','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°26','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°27','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°28','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°1','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°3','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°4','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°5','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°6','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°7','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°8','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°9','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°10','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°11','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°12','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°13','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°14','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°15','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°16','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°1','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°3','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°4','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°5','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°6','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°7','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°8','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°9','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°10','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°11','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°12','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°1','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°3','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°4','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°5','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°6','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°7','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°8','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°9','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°10','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°11','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°12','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°13','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Sword Art Online Aincrad n°1','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Aincrad n°2','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°1','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°2','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°3','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Calibur','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Mothers Rosario n°1','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Mothers Rosario n°2','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Mothers Rosario n°3','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),