CREATE TABLE `livros` (
  id int not null auto_increment primary key,
  titulo varchar(90),
  categoria varchar(60),
  autor varchar(60),
  editora varchar(60),
  tipo varchar(60),
  estado tinyint(1),
  recebido boolean,
  pathi varchar(90),
  relation int,
  valor int);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°1','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°2','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°3','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°4','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°5','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°6','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°7','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°8','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°9','ventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°10','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°11','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°12','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°13','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°14','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°15','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°17','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°19','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°20','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°21','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°22','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°23','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°24','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°25','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°26','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°27','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°28','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°29','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°30','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°31','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°32','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°33','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°34','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°35','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°36','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°37','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°38','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°39','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°41','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°42','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°43','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°44','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°45','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°46','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°47','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°48','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°49','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°50','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°51','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°52','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°53','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°54','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°55','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°56','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°57','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°59','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°61','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°62','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°64','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°65','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°66','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°67','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°68','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°69','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°70','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°71','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°72','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°73','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°74','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°75','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°76','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°77','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°78','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°79','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°80','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°81','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°82','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°83','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°84','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°85','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°86','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°87','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°88','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°89','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°90','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°91','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°92','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°93','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°94','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°95','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°96','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°97','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°98','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°99','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°100','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°101','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°102','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°103','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°104','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°105','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°106','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°107','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°108','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°109','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece n°72','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece n°1','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°2','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°3','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°4','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°5','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°6','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°7','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°8','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°9','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°9','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°10','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°11','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°12','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°13','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°14','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°15','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°16','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°17','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°18','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°19','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°20','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°21','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°22','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°23','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°24','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°25','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°26','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°27','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°28','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°29','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°30','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°31','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°32','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°33','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°34','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°35','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°36','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°37','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°38','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°39','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°40','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°41','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°42','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°43','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°44','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°45','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°46','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°47','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°48','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°49','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°50','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°51','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°52','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°53','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°54','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°55','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°56','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°57','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°58','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°59','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°60','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°61','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°62','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°63','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°64','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°65','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°66','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°67','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°68','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°69','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2),
(default,'One piece n°70','Aventura','Eiichiro Oda','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'One piece Yellow Grandes Elementos','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Grande Arquivo de Dados','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Grande Arquivo de Dados','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Red Grandes Personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Red Grandes Personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Green Peças Secretas','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Green Peças Secretas','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Wanted!','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece Blue Deep Mundo dos personagens','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°1','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°2','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°3','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°4','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°5','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°6','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°7','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°7','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°9','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°10','Aventura','Eiichiro Oda','Panini','Manga',1,1,null,2),
(default,'One piece 3 em 1 n°11','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°12','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°13','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°14','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°15','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°16','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°17','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°18','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2),
(default,'One piece 3 em 1 n°19','Aventura','Eiichiro Oda','Panini','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Dragon Ball n°1','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°2','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°3','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°4','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°5','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°6','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°7','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°8','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°9','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°10','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°11','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°12','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°13','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°14','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°15','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°16','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°17','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°18','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°19','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°20','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°21','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°22','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°23','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°24','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°25','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°26','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°27','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°28','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°29','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°30','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°31','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball n°32','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Dragon Ball Z n°1','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°2','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°3','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°4','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°5','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°6','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°7','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°8','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°9','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°10','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°11','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°12','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°13','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°14','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°15','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°16','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°17','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°18','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°19','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°20','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°21','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°22','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°23','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°24','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°25','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°26','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°27','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°28','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°29','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°30','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°31','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°32','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°33','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°34','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°35','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°35','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°36','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°37','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°38','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°39','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°40','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°41','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°42','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°43','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°44','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°45','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°46','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°47','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°48','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°49','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°50','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2),
(default,'Dragon Ball Z n°51','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,	'Dragon Ball n°1','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°2','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°3','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°4','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°5','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°6','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°7','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°8','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°9','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°10','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°11','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°12','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°13','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°14','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°15','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°16','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°17','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°18','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°19','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°20','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°21','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°22','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°23','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°24','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°25','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°26','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°27','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°28','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°29','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°30','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°31','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°32','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°33','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°34','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°35','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°36','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°37','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°38','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°39','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°40','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°41','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2),
(default,	'Dragon Ball n°42','Aventura','Akira Toriyama','Panini Comics','Manga',1,1,null,2);


insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,	'Enciclopédia Dragon Ball Z A lenda de Son Goku','Aventura','Akira Toriyama','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°3','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°4','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°5','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°6','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°7','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°8','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°9','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°10','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°11','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°12','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°13','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°14','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°15','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°16','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°17','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°18','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°19','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°20','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°21','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°22','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°23','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°24','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°25','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°26','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°27','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°28','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°29','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°30','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°31','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°32','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°33','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°34','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°35','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°36','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°37','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°38','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°39','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°40','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°41','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°42','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°43','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°44','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°45','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°46','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°47','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°48','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°1','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°3','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°4','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°5','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°6','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°7','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°8','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°9','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°10','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°11','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°12','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°13','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°14','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°15','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°16','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°17','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°18','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°19','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°20','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°21','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°22','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°23','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas A Saga de Hades n°24','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco Episódio G n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°3','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°4','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°5','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°6','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°7','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°8','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°9','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°10','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°11','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°12','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°13','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°13','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°14','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°14','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°15','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°15','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°16','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°17','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°18','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°19','Aventura','Masami Kurumada','Conrad','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco Episódio G n°20','Aventura','Masami Kurumada','Conrad','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco Anime Classies I n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Anime Classies I n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Anime Classies II n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco Anime Classies II n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Gigantomaquia n°1','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Gigantomaquia n°2','Aventura','Masami Kurumada','Conrad','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco n°1','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°2','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°3','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°4','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°5','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°6','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°7','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°8','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°9','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°10','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°11','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°12','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°13','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°14','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°15','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°16','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°17','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°18','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°19','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°20','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°21','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°22','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°23','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°24','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°25','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°26','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°27','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco n°28','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°1','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°3','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°4','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°5','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°6','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°7','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°8','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°9','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°10','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°11','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°12','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°13','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°14','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°15','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco The Lost Canvas Gaiden n°16','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°1','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°3','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°4','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°5','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°6','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°7','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°8','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°9','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°10','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°11','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Next Dimension A Saga de Hades n°12','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°1','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°2','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°3','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°4','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°5','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°6','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°7','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°8','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°9','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°10','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°11','Aventura','Masami Kurumada','JBC','Manga',1,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°12','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2),
(default,'Os Cavaleiro do Zodíaco - Saintia Shô n°13','Aventura','Masami Kurumada','JBC','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Sword Art Online Aincrad n°1','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Aincrad n°2','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°1','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°2','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°3','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Calibur','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Mothers Rosario n°1','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Mothers Rosario n°2','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Mothers Rosario n°3','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Sword Art Online Girlz Operations n°1','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Girlz Operations n°2','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Girlz Operations n°3','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Girlz Operations n°4','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Girlz Operations n°5','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Girlz Operations n°6','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Girlz Operations n°7','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2),
(default,'Sword Art Online Girlz Operations n°8','Aventura','Reki Kawahara','Panini','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Sword Art Online Aincrad n°1','Aventura','Reki Kawahara','Panini Books','Manga',0,1,null,2),
(default,'Sword Art Online Aincrad n°2','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Fairy Dance n°3','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Fairy Dance n°3','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Fairy Dance n°4','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°5','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Phantom Bullet n°6','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°7','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°8','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°9','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°10','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°11','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°12','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°13','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°14','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°15','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°16','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°17','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°18','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Early and Late n°19','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Sword Art Online Fairy Dance n°1','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Fairy Dance n°2','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Fairy Dance n°3','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Sword Art Online Progressive n°1','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive n°2','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive n°3','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive n°3','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive n°4','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive n°5','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive n°6','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive n°7','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Sword Art Online Progressive Barcarole Of Froth n°1','Aventura','Reki Kawahara','Panini Books','Manga',1,1,null,2),
(default,'Sword Art Online Progressive Barcarole Of Froth n°2','Aventura','Reki Kawahara','Panini Books','Manga',1,0,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Naruto n°1','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°2','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°3','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°4','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°5','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°6','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°7','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°8','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°9','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°10','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°11','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°12','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°12','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°13','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°14','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°15','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°16','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°17','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°18','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°19','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°20','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°21','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°22','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°23','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°24','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°25','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°26','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°27','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°28','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°29','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°30','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°31','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°32','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°33','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°34','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°35','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°36','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°37','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°38','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°39','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°40','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°41','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°42','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°43','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°44','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°45','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°46','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°47','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°48','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°49','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°50','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°51','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°52','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°53','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°54','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°55','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°56','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°57','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°58','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°59','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°60','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°61','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°62','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°63','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°64','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°65','Aventura','Masashi Kishimoto','Panini Comics','Manga',0,1,null,2),
(default,'Naruto n°66','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°67','Aventura','Masashi Kishimoto','Panini Comics','Manga',0,1,null,2),
(default,'Naruto n°68','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°69','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto n°70','Aventura','Masashi Kishimoto','Panini Comics','Manga',0,1,null,2),
(default,'Naruto n°71','Aventura','Masashi Kishimoto','Panini Comics','Manga',0,1,null,2),
(default,'Naruto n°72','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Naruto - O Livro Secreto de Confronto','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto - O Livro Secreto da Batalha','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto - O Livro Secreto da Formação','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto A História Secreta de Kakashi - O Relâmpago Sob o Céu Gélido','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto A Nuvem que Paira no Silêncio da Escuridão','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Shonen Jump Naruto Ninja Council 3 Official Game Guide','Aventura','Masashi Kishimoto','Prima Games','Manga',1,1,null,2),
(default,'Naruto - A História secreta de Sakura','Aventura','Masashi Kishimoto','Prima Games','Manga',1,1,null,2),
(default,'Naruto - A História secreta de Konoha','Aventura','Masashi Kishimoto','Books Romance','Manga',1,1,null,2),
(default,'Naruto Gaiden - O Sétimo hokage e a Lua Floresce Vermelha','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto - A História Secreta de Garra - A ilusão na Tempestade de Areia','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto - O Livro Secreto do Guerreiro','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto - A História Secreta da Akatsuki','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto A verdadeira História de Itachi','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto A verdadeira História de Sasuke','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,1,null,2),
(default,'Naruto - A verdadeira História da Folha 10','Aventura','Masashi Kishimoto','Panini Comics','Manga',1,0,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Fairy Tail n°1','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°2','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°3','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°4','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°4','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°5','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°6','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°7','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°8','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°9','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°10','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°11','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°12','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°13','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°14','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°15','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°16','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°17','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°18','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°19','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°20','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°20','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°21','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°22','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°23','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°24','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°25','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°26','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°27','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°28','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°29','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°30','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°31','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°32','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°33','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°34','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°35','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°36','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°37','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°38','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°39','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°40','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°41','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°42','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°43','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°44','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°45','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°46','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°47','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°48','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°49','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°50','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°51','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°52','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°53','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°54','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°55','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°56','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°57','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°58','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°59','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°60','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°61','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°62','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail n°63','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Fairy Tail Gaiden - Dragões Gêmeos da Sabertooth n°1','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail Gaiden - Rota do Cavaleiro n°2','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail Gaiden - Brilho do Grande Relâmpago n°3','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Fairy Tail Zero n°1','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Fairy Tail Blue Mistral n°1','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail Blue Mistral n°2','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail Blue Mistral n°3','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail Blue Mistral n°4','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Fairy Tail Ice Trail n°1','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2),
(default,'Fairy Tail Ice Trail n°2','Aventura','Hiro Mashima','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'Samurai X n°1',''Ação'','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°2','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°3','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°4','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°5','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°6','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°7','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°8','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°9','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°10','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°11','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°12','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°13','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°14','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°15','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°16','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°17','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°18','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°19','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°20','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°21','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°22','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°23','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°24','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°25','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°26','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°27','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°28','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°29','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°30','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°31','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°32','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°33','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°34','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°35','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°36','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°37','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°38','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°39','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°40','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°41','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°42','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°43','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°44','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°45','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°46','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°47','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°48','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°49','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°50','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°51','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°52','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°53','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°54','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°55','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X n°56','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X - Especial Yariku','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X - Crônicas de um samurai na era Meiji n°1','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Samurai X - Crônicas de um samurai na era Meiji n°2','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°1','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°2','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°3','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°3','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°4','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°5','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°6','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°7','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°8','Ação','Nobuhiro Watsuki','JBC','Manga',0,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°9','Ação','Nobuhiro Watsuki','JBC','Manga',0,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°10','Ação','Nobuhiro Watsuki','JBC','Manga',0,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°11','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°12','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°13','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°14','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°15','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°16','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°17','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°18','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°19','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°20','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°21','Ação','Nobuhiro Watsuki','JBC','Manga',0,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°22','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°23','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°24','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°25','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°26','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°27','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Crônicas da Era Meiji X n°28','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'A Sakabatou de Yahiko Especial','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2),
(default,'Rurouni Kenshin Tajuitsuban n°1','Ação','Nobuhiro Watsuki','Versão do autor','Manga',1,1,null,2),
(default,'Rurouni Kenshin Tajuitsuban n°2','Ação','Nobuhiro Watsuki','Versão do autor','Manga',1,1,null,2),
(default,'Samurai X - Kenshin KADEN','Ação','Nobuhiro Watsuki','JBC','Manga',1,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
(default,'FullMetal Alchemist n°1','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°2','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°3','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°4','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°5','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°6','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°7','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°8','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°9','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°10','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°11','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°12','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°13','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°14','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°15','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°16','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°17','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°18','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°19','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°20','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°21','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°22','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°23','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°24','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°25','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°26','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°27','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°28','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°29','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°30','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°31','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°32','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°33','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°34','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°35','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°36','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°37','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°38','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°39','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°40','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°41','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°42','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°43','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°44','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°45','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°46','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°47','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°48','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°49','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°50','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist n°51','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°52','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°53','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist n°54','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2),
(default,'FullMetal Alchemist Guia Completo 1','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist Guia Completo 2','Ação','Hiromu Arakawa','JBC','Manga',1,1,null,2),
(default,'FullMetal Alchemist Guia Completo 3','Ação','Hiromu Arakawa','JBC','Manga',0,1,null,2);

insert into livros (id,titulo,categoria,autor,editora,tipo,estado,recebido,pathi,relation) values
